ViewModels/ShortenModel.cs
using System.ComponentModel.DataAnnotations;

namespace UrlShortener.ViewModels
{
    public class ShortenModel
    {
        [Required]
        [RegularExpression(@"^http(s)?://([\w-]+.)+[\w-]+(/[\w- ./?%&=])?$")]
        public string Url { get; set; }
        
        public string ShortenedUrl { get; set; }

    }
}

Controllers/UrlController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UrlShortener.Data.Repositories;
using UrlShortener.Services;
using UrlShortener.ViewModels;

namespace UrlShortener.Controllers
{
    [Route("/")]
    public class UrlController : Controller
    {

        private readonly IShorteningService _service;
        private readonly IUrlRepository _urlRepo;

        public UrlController(IShorteningService service, IUrlRepository urlRepo)
        {
            _service = service;
            _urlRepo = urlRepo;
        }

        [HttpGet("/")]
        public ViewResult Index()
        {
            return View();
        }

        [HttpPost("shorten")]
        public ViewResult Shorten(ShortenModel model)
        {
            if (!ModelState.IsValid)
                return View("Index", model);

            model.ShortenedUrl = _service.ShortenAndStore(model.Url);
            return View(model);
        }

        [HttpGet("/u/{hash}")]
        public IActionResult RedirectUrl(string hash)
        {
            return Redirect(_urlRepo.getUrl(hash));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title></title>
  <link href="https://unpkg.com/tailwindcss@@^1.0/dist/tailwind.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Damion|Handlee&display=swap" rel="stylesheet">
</head>
<body>
    @RenderBody()
</body>
</html>

Views/Url/Index.cshtml
@model ShortenModel

@{
    Layout = "_Layout";
}

<div class="h-12 flex items-stretch">
    <div class="container mx-auto flex items-center"><p class="font-bold font-italic">UrlShortener</p></div>
</div>

<div class="container flex mx-auto justify-center p-8 mt-8">
    <p class="text-4xl font-semibold">Shorten your URL!</p>
</div>

<div class="flex container mx-auto justify-center mt-8">
    <form class="flex" asp-controller="Url" asp-action="Shorten" method="POST">
        @if (ViewData.ModelState.IsValid) {
            <input class="bg-gray-200 rounded-l-lg text-2xl py-4 px-8 hover:bg-gray-300 active:bg-gray-300 outline-none" asp-for="Url" type="text" placeholder="Enter your link here" autocomplete="off"/>
        } else {
            <input class="bg-red-200 text-red-700 rounded-l-lg text-2xl py-4 px-8 hover:bg-red-300 outline-none" asp-for="Url" type="text" placeholder="Enter your link here" autocomplete="off"/>
        }
        <button type="submit" class="text-2xl bg-blue-500 hover:bg-blue-700 text-white font-semibold py-4 px-8 rounded-r-lg">Shorten</button>
    </form>
</div>

Views/Url/RedirectUrl.cshtml
@model string

@{
    Layout = "_Layout";
}

Bismillah

Views/Url/Shorten.cshtml
@model ShortenModel

@{
    Layout = "_Layout";
}

<div class="h-12 flex items-stretch">
    <div class="container mx-auto flex items-center"><p class="font-bold font-italic">UrlShortener</p></div>
</div>

<div class="container flex mx-auto justify-center p-8 mt-8">
    <p class="text-4xl font-semibold">Here is your Shortened URL!</p>
</div>

<div class="flex container mx-auto justify-center mt-8">
    <div class="flex">
        <a href=@Model.ShortenedUrl class="bg-gray-200 rounded-l-lg text-2xl py-4 px-8 hover:bg-gray-300">@Model.ShortenedUrl</a href="@Model.ShortenedUrl">
        <button type="submit" class="text-2xl bg-blue-500 hover:bg-blue-700 text-white font-bold py-4 px-8 rounded-r-lg">Copy</button>
    </div>
</div>